import { supabase } from '@/lib/supabase';
import type { PatternSource, PrepareQuestion } from '@/lib/supabase';

// Direct port of the web app's src/lib/api/questions.ts — pure Supabase
// queries, nothing to adapt.

export async function fetchQuestionsForAppointment(appointmentId: string): Promise<PrepareQuestion[]> {
  const { data, error } = await supabase
    .from('prepare_questions')
    .select('*')
    .eq('appointment_id', appointmentId)
    .order('is_priority', { ascending: false })
    .order('sort_order', { ascending: true });

  if (error) throw error;
  return data || [];
}

/** Create a new question (appends to end of list for given priority group). */
export async function createQuestion(
  userId: string,
  appointmentId: string,
  questionText: string,
  isPriority: boolean = false,
  isAutoGenerated: boolean = false,
  sourcePatternId?: string,
  sourcePatternSource?: PatternSource
): Promise<PrepareQuestion> {
  const { data: existing } = await supabase
    .from('prepare_questions')
    .select('sort_order')
    .eq('appointment_id', appointmentId)
    .order('sort_order', { ascending: false })
    .limit(1)
    .maybeSingle();

  const sortOrder = (existing?.sort_order ?? -1) + 1;

  const { data, error } = await supabase
    .from('prepare_questions')
    .insert({
      user_id: userId,
      appointment_id: appointmentId,
      question_text: questionText,
      is_priority: isPriority,
      is_auto_generated: isAutoGenerated,
      source_pattern_id: sourcePatternId ?? null,
      source_pattern_source: sourcePatternSource ?? null,
      sort_order: sortOrder,
    })
    .select()
    .single();

  if (error) throw error;
  return data;
}

export async function updateQuestion(
  questionId: string,
  updates: Partial<Omit<PrepareQuestion, 'id' | 'user_id' | 'created_at'>>
): Promise<PrepareQuestion> {
  const { data, error } = await supabase
    .from('prepare_questions')
    .update(updates)
    .eq('id', questionId)
    .select()
    .single();

  if (error) throw error;
  return data;
}

/** Batch update sort_order for a list of question IDs (for reordering). */
export async function reorderQuestions(questionIds: string[], isPriority: boolean): Promise<void> {
  await Promise.all(
    questionIds.map((id, index) =>
      supabase.from('prepare_questions').update({ sort_order: index, is_priority: isPriority }).eq('id', id)
    )
  );
}

export async function deleteQuestion(questionId: string): Promise<void> {
  const { error } = await supabase.from('prepare_questions').delete().eq('id', questionId);

  if (error) throw error;
}

export async function markQuestionAddressed(questionId: string, isAddressed: boolean): Promise<PrepareQuestion> {
  return updateQuestion(questionId, { is_addressed: isAddressed });
}
